title: Hiï¼I'm EvenZHAng.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/simple-life" # the subpath of your site, e.g. /blog
url: "https://evenzhanglll.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Even ZHAng # add your name
author-img: evenzhang.jpg # add your photo
about-author: I am a student focusing on web development and graffity art.  # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: evenzhanglll # add your Github handle

email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
